/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { logsGetConsole } from "../funcs/logsGetConsole.js";
import { logsGetCron } from "../funcs/logsGetCron.js";
import { logsGetHttp } from "../funcs/logsGetHttp.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Logs extends ClientSDK {
  async getCron(
    request: operations.GetCronLogsRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(logsGetCron(
      this,
      request,
      options,
    ));
  }

  async getHttp(
    request: operations.GetHttpLogsRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(logsGetHttp(
      this,
      request,
      options,
    ));
  }

  async getConsole(
    request: operations.GetConsoleLogsRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(logsGetConsole(
      this,
      request,
      options,
    ));
  }
}
