/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetAppRequest = {
  app: string;
};

/** @internal */
export const GetAppRequest$inboundSchema: z.ZodType<
  GetAppRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  app: z.string(),
});

/** @internal */
export type GetAppRequest$Outbound = {
  app: string;
};

/** @internal */
export const GetAppRequest$outboundSchema: z.ZodType<
  GetAppRequest$Outbound,
  z.ZodTypeDef,
  GetAppRequest
> = z.object({
  app: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetAppRequest$ {
  /** @deprecated use `GetAppRequest$inboundSchema` instead. */
  export const inboundSchema = GetAppRequest$inboundSchema;
  /** @deprecated use `GetAppRequest$outboundSchema` instead. */
  export const outboundSchema = GetAppRequest$outboundSchema;
  /** @deprecated use `GetAppRequest$Outbound` instead. */
  export type Outbound = GetAppRequest$Outbound;
}
