/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetConsoleLogsRequest = {
  /**
   * Filter logs by app
   */
  app?: string | undefined;
};

/** @internal */
export const GetConsoleLogsRequest$inboundSchema: z.ZodType<
  GetConsoleLogsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  app: z.string().optional(),
});

/** @internal */
export type GetConsoleLogsRequest$Outbound = {
  app?: string | undefined;
};

/** @internal */
export const GetConsoleLogsRequest$outboundSchema: z.ZodType<
  GetConsoleLogsRequest$Outbound,
  z.ZodTypeDef,
  GetConsoleLogsRequest
> = z.object({
  app: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetConsoleLogsRequest$ {
  /** @deprecated use `GetConsoleLogsRequest$inboundSchema` instead. */
  export const inboundSchema = GetConsoleLogsRequest$inboundSchema;
  /** @deprecated use `GetConsoleLogsRequest$outboundSchema` instead. */
  export const outboundSchema = GetConsoleLogsRequest$outboundSchema;
  /** @deprecated use `GetConsoleLogsRequest$Outbound` instead. */
  export type Outbound = GetConsoleLogsRequest$Outbound;
}
