/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type GetHttpLogsRequest = {
  /**
   * Filter logs by host
   */
  host?: string | undefined;
};

/** @internal */
export const GetHttpLogsRequest$inboundSchema: z.ZodType<
  GetHttpLogsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  host: z.string().optional(),
});

/** @internal */
export type GetHttpLogsRequest$Outbound = {
  host?: string | undefined;
};

/** @internal */
export const GetHttpLogsRequest$outboundSchema: z.ZodType<
  GetHttpLogsRequest$Outbound,
  z.ZodTypeDef,
  GetHttpLogsRequest
> = z.object({
  host: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetHttpLogsRequest$ {
  /** @deprecated use `GetHttpLogsRequest$inboundSchema` instead. */
  export const inboundSchema = GetHttpLogsRequest$inboundSchema;
  /** @deprecated use `GetHttpLogsRequest$outboundSchema` instead. */
  export const outboundSchema = GetHttpLogsRequest$outboundSchema;
  /** @deprecated use `GetHttpLogsRequest$Outbound` instead. */
  export type Outbound = GetHttpLogsRequest$Outbound;
}
