/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import * as components from "../components/index.js";

export type RunAppRequestBody = {
  args: Array<string>;
};

export type RunAppRequest = {
  app: string;
  requestBody?: RunAppRequestBody | undefined;
};

export type RunAppResponse = components.CommandOutput | string;

/** @internal */
export const RunAppRequestBody$inboundSchema: z.ZodType<
  RunAppRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  args: z.array(z.string()),
});

/** @internal */
export type RunAppRequestBody$Outbound = {
  args: Array<string>;
};

/** @internal */
export const RunAppRequestBody$outboundSchema: z.ZodType<
  RunAppRequestBody$Outbound,
  z.ZodTypeDef,
  RunAppRequestBody
> = z.object({
  args: z.array(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunAppRequestBody$ {
  /** @deprecated use `RunAppRequestBody$inboundSchema` instead. */
  export const inboundSchema = RunAppRequestBody$inboundSchema;
  /** @deprecated use `RunAppRequestBody$outboundSchema` instead. */
  export const outboundSchema = RunAppRequestBody$outboundSchema;
  /** @deprecated use `RunAppRequestBody$Outbound` instead. */
  export type Outbound = RunAppRequestBody$Outbound;
}

/** @internal */
export const RunAppRequest$inboundSchema: z.ZodType<
  RunAppRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  app: z.string(),
  RequestBody: z.lazy(() => RunAppRequestBody$inboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type RunAppRequest$Outbound = {
  app: string;
  RequestBody?: RunAppRequestBody$Outbound | undefined;
};

/** @internal */
export const RunAppRequest$outboundSchema: z.ZodType<
  RunAppRequest$Outbound,
  z.ZodTypeDef,
  RunAppRequest
> = z.object({
  app: z.string(),
  requestBody: z.lazy(() => RunAppRequestBody$outboundSchema).optional(),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunAppRequest$ {
  /** @deprecated use `RunAppRequest$inboundSchema` instead. */
  export const inboundSchema = RunAppRequest$inboundSchema;
  /** @deprecated use `RunAppRequest$outboundSchema` instead. */
  export const outboundSchema = RunAppRequest$outboundSchema;
  /** @deprecated use `RunAppRequest$Outbound` instead. */
  export type Outbound = RunAppRequest$Outbound;
}

/** @internal */
export const RunAppResponse$inboundSchema: z.ZodType<
  RunAppResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.CommandOutput$inboundSchema, z.string()]);

/** @internal */
export type RunAppResponse$Outbound =
  | components.CommandOutput$Outbound
  | string;

/** @internal */
export const RunAppResponse$outboundSchema: z.ZodType<
  RunAppResponse$Outbound,
  z.ZodTypeDef,
  RunAppResponse
> = z.union([components.CommandOutput$outboundSchema, z.string()]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace RunAppResponse$ {
  /** @deprecated use `RunAppResponse$inboundSchema` instead. */
  export const inboundSchema = RunAppResponse$inboundSchema;
  /** @deprecated use `RunAppResponse$outboundSchema` instead. */
  export const outboundSchema = RunAppResponse$outboundSchema;
  /** @deprecated use `RunAppResponse$Outbound` instead. */
  export type Outbound = RunAppResponse$Outbound;
}
