/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type Manifest = {};

export type App = {
  name: string;
  url: string;
  manifest?: Manifest | undefined;
};

/** @internal */
export const Manifest$inboundSchema: z.ZodType<
  Manifest,
  z.ZodTypeDef,
  unknown
> = z.object({});

/** @internal */
export type Manifest$Outbound = {};

/** @internal */
export const Manifest$outboundSchema: z.ZodType<
  Manifest$Outbound,
  z.ZodTypeDef,
  Manifest
> = z.object({});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace Manifest$ {
  /** @deprecated use `Manifest$inboundSchema` instead. */
  export const inboundSchema = Manifest$inboundSchema;
  /** @deprecated use `Manifest$outboundSchema` instead. */
  export const outboundSchema = Manifest$outboundSchema;
  /** @deprecated use `Manifest$Outbound` instead. */
  export type Outbound = Manifest$Outbound;
}

/** @internal */
export const App$inboundSchema: z.ZodType<App, z.ZodTypeDef, unknown> = z
  .object({
    name: z.string(),
    url: z.string(),
    manifest: z.lazy(() => Manifest$inboundSchema).optional(),
  });

/** @internal */
export type App$Outbound = {
  name: string;
  url: string;
  manifest?: Manifest$Outbound | undefined;
};

/** @internal */
export const App$outboundSchema: z.ZodType<App$Outbound, z.ZodTypeDef, App> = z
  .object({
    name: z.string(),
    url: z.string(),
    manifest: z.lazy(() => Manifest$outboundSchema).optional(),
  });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace App$ {
  /** @deprecated use `App$inboundSchema` instead. */
  export const inboundSchema = App$inboundSchema;
  /** @deprecated use `App$outboundSchema` instead. */
  export const outboundSchema = App$outboundSchema;
  /** @deprecated use `App$Outbound` instead. */
  export type Outbound = App$Outbound;
}
