/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";

export type CommandOutput = {
  success: boolean;
  code: number;
  stdout: string;
  stderr: string;
};

/** @internal */
export const CommandOutput$inboundSchema: z.ZodType<
  CommandOutput,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
  code: z.number().int(),
  stdout: z.string(),
  stderr: z.string(),
});

/** @internal */
export type CommandOutput$Outbound = {
  success: boolean;
  code: number;
  stdout: string;
  stderr: string;
};

/** @internal */
export const CommandOutput$outboundSchema: z.ZodType<
  CommandOutput$Outbound,
  z.ZodTypeDef,
  CommandOutput
> = z.object({
  success: z.boolean(),
  code: z.number().int(),
  stdout: z.string(),
  stderr: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CommandOutput$ {
  /** @deprecated use `CommandOutput$inboundSchema` instead. */
  export const inboundSchema = CommandOutput$inboundSchema;
  /** @deprecated use `CommandOutput$outboundSchema` instead. */
  export const outboundSchema = CommandOutput$outboundSchema;
  /** @deprecated use `CommandOutput$Outbound` instead. */
  export type Outbound = CommandOutput$Outbound;
}
